### ISSUE TITLE
Imported .tres don't work

### ISSUE THREAD

**Issue by mathewcst** [jordigcs/crunch-gd#2]
I've tried using this tool.

![image](https://user-images.githubusercontent.com/5620645/211217796-fe67cef1-caf4-4512-8d25-61e06ec483d7.png)

When I copy and paste the folder into Godot, I can't open/use the .tres files

![image](https://user-images.githubusercontent.com/5620645/211217812-4639a87c-bec1-4884-9758-3c7aef72948e.png)

Using Godot 4 beta 10
Windows 10

**Comment by mathewcst** [comment]
Ok my bad. It was pathing problem. It considers the path when generating as the root (`res://`) so I have to use the same path in my project structre.

**Comment by jordigulley** [comment]
All resource files generated point to the atlas relative to your project root. 

I'll make the output argument require a path to your project folder, and add a separate arg for the relative path the atlas will reside at to make this more clear.

Thanks for pointing this out!
